// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mvc1.Data;

namespace mvc1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201208005840_AddTourneyToDatabase")]
    partial class AddTourneyToDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("mvc1.Models.Skier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkierNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Skier");
                });

            modelBuilder.Entity("mvc1.Models.Tourney", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TourneyNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tourney");
                });
#pragma warning restore 612, 618
        }
    }
}
